-- Core weekly partner dataset used by the report.
-- The window stops at the start of the current week so every reported week is
-- complete; a partial week-to-date week would understate the latest bar and
-- break the week-over-week comparisons.
-- The deep-dive slices (daily, cities, objectives, campaigns, refund reasons)
-- are generated by refresh_data.py, which uses the same scope and definitions.
WITH base AS (
  SELECT
    DATE_TRUNC('week', f.order_created_date) AS week_start,
    CASE
      WHEN p.brand_name = 'OKKO MARKET' THEN p.brand_name
      ELSE COALESCE(p.group_name, p.brand_name, f.provider_name)
    END AS partner,
    f.order_state,
    f.order_gmv_eur,
    f.demand_incentives_eur,
    f.demand_refunds_eur,
    f.total_refunds_eur
  FROM main.ng_delivery.fact_order_delivery f
  JOIN main.ng_delivery.dim_provider_v2 p
    ON f.provider_id = p.provider_id
  WHERE f.city_country_code = 'ua'
    AND (
      p.delivery_vertical LIKE 'store_3p%'
      OR p.group_name IN ('ANRI-PHARM', 'BRSM', 'VAPORS', 'PIVASOV')
    )
    AND f.order_created_date >= DATE_ADD(DATE_TRUNC('week', CURRENT_DATE()), -91)
    AND f.order_created_date < DATE_TRUNC('week', CURRENT_DATE())
)
SELECT
  CAST(week_start AS DATE) AS week_start,
  partner,
  SUM(CASE WHEN order_state = 'delivered' THEN 1 ELSE 0 END) AS orders,
  ROUND(SUM(CASE WHEN order_state = 'delivered' THEN order_gmv_eur ELSE 0 END), 2) AS gmv_eur,
  ROUND(SUM(CASE WHEN order_state = 'delivered' THEN COALESCE(demand_incentives_eur, 0) ELSE 0 END), 2) AS demand_incentives_eur,
  ROUND(SUM(COALESCE(demand_refunds_eur, 0)), 2) AS demand_refunds_eur,
  ROUND(SUM(COALESCE(total_refunds_eur, 0)), 2) AS total_refunds_eur,
  SUM(CASE WHEN order_state = 'delivered' AND COALESCE(demand_incentives_eur, 0) != 0 THEN 1 ELSE 0 END) AS incentive_orders,
  SUM(CASE WHEN COALESCE(demand_refunds_eur, 0) != 0 THEN 1 ELSE 0 END) AS demand_refund_orders
FROM base
GROUP BY week_start, partner
HAVING orders > 0 OR demand_refunds_eur != 0
ORDER BY week_start, gmv_eur DESC;

-- Last full week (10–16 Aug) commission and CM L1 (CP Margin) from fact_provider_weekly.
-- Commission € = GMV-weighted commission amount; Commission % = Commission of GMV.
-- CM L1 = total_contribution_profit_eur / total_gmv_before_discounts_eur.
SELECT
  CASE
    WHEN p.brand_name = 'OKKO MARKET' THEN p.brand_name
    ELSE COALESCE(p.group_name, p.brand_name)
  END AS partner,
  ROUND(SUM(f.provider_commission_gmv_share_value * f.provider_commission_gmv_share_weight), 2) AS commission_eur,
  ROUND(SUM(f.provider_commission_gmv_share_value * f.provider_commission_gmv_share_weight)
    / NULLIF(SUM(f.provider_commission_gmv_share_weight), 0) * 100, 1) AS commission_gmv_pct,
  ROUND(SUM(f.total_contribution_profit_eur), 2) AS cm_l1_eur,
  ROUND(SUM(f.total_contribution_profit_eur)
    / NULLIF(SUM(f.total_gmv_before_discounts_eur), 0) * 100, 2) AS cm_l1_pct
FROM main.ng_delivery.fact_provider_weekly f
JOIN main.ng_delivery.dim_provider_v2 p
  ON f.provider_id = p.provider_id
WHERE p.country_code = 'ua'
  AND (
    p.delivery_vertical LIKE 'store_3p%'
    OR p.group_name IN ('ANRI-PHARM', 'BRSM', 'VAPORS', 'PIVASOV')
  )
  AND f.metric_timestamp_local = DATE '2026-08-10'
GROUP BY 1
HAVING SUM(f.delivered_orders_count) > 0
ORDER BY commission_eur DESC NULLS LAST;

-- Prior full week (3–9 Aug) commission and CM L1.
SELECT
  CASE
    WHEN p.brand_name = 'OKKO MARKET' THEN p.brand_name
    ELSE COALESCE(p.group_name, p.brand_name)
  END AS partner,
  ROUND(SUM(f.provider_commission_gmv_share_value * f.provider_commission_gmv_share_weight), 2) AS commission_eur,
  ROUND(SUM(f.provider_commission_gmv_share_value * f.provider_commission_gmv_share_weight)
    / NULLIF(SUM(f.provider_commission_gmv_share_weight), 0) * 100, 1) AS commission_gmv_pct,
  ROUND(SUM(f.total_contribution_profit_eur), 2) AS cm_l1_eur,
  ROUND(SUM(f.total_contribution_profit_eur)
    / NULLIF(SUM(f.total_gmv_before_discounts_eur), 0) * 100, 2) AS cm_l1_pct
FROM main.ng_delivery.fact_provider_weekly f
JOIN main.ng_delivery.dim_provider_v2 p
  ON f.provider_id = p.provider_id
WHERE p.country_code = 'ua'
  AND (
    p.delivery_vertical LIKE 'store_3p%'
    OR p.group_name IN ('ANRI-PHARM', 'BRSM', 'VAPORS', 'PIVASOV')
  )
  AND f.metric_timestamp_local = DATE '2026-08-03'
GROUP BY 1
HAVING SUM(f.delivered_orders_count) > 0
ORDER BY commission_eur DESC NULLS LAST;

-- All partners table base: orders, GMV, demand incentives and refunds per partner
-- for the last full week (10–16 Aug) and prior full week (3–9 Aug) from fact_order_delivery.
-- Orders/GMV/incentives use delivered orders; refunds include all order states.
-- Last-week delivered orders total 12,381.
WITH base AS (
  SELECT
    CASE WHEN p.brand_name = 'OKKO MARKET' THEN p.brand_name
         ELSE COALESCE(p.group_name, p.brand_name, f.provider_name) END AS partner,
    CASE
      WHEN f.order_created_date BETWEEN DATE '2026-08-10' AND DATE '2026-08-16' THEN 'last_week'
      WHEN f.order_created_date BETWEEN DATE '2026-08-03' AND DATE '2026-08-09' THEN 'prior_week'
    END AS wk,
    f.order_state, f.order_gmv_eur, f.demand_incentives_eur, f.demand_refunds_eur
  FROM main.ng_delivery.fact_order_delivery f
  JOIN main.ng_delivery.dim_provider_v2 p
    ON f.provider_id = p.provider_id
  WHERE f.city_country_code = 'ua'
    AND (
      p.delivery_vertical LIKE 'store_3p%'
      OR p.group_name IN ('ANRI-PHARM', 'BRSM', 'VAPORS', 'PIVASOV')
    )
    AND f.order_created_date BETWEEN DATE '2026-08-03' AND DATE '2026-08-16'
)
SELECT
  wk,
  partner,
  SUM(CASE WHEN order_state = 'delivered' THEN 1 ELSE 0 END) AS orders,
  ROUND(SUM(CASE WHEN order_state = 'delivered' THEN order_gmv_eur ELSE 0 END), 2) AS gmv_eur,
  ROUND(SUM(CASE WHEN order_state = 'delivered' THEN COALESCE(demand_incentives_eur, 0) ELSE 0 END), 2) AS demand_incentives_eur,
  ROUND(SUM(COALESCE(demand_refunds_eur, 0)), 2) AS demand_refunds_eur
FROM base
WHERE wk IS NOT NULL
GROUP BY wk, partner
HAVING orders > 0 OR demand_refunds_eur <> 0
ORDER BY wk, gmv_eur DESC;
